version: "3.9"

volumes:
  db_data:
  alembic_data:

services:
  db:
    image: postgres:13
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    env_file:
      - .env

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - alembic_data:/app/migrations
